# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppNC2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QPushButton, QToolTip, QLineEdit, QPlainTextEdit, QVBoxLayout


class Ui_Fertilidade(object):
    def setupUi(self, Fertilidade):
        Fertilidade.setObjectName("Fertilidade")
        Fertilidade.resize(766, 555)
        self.centralwidget = QtWidgets.QWidget(Fertilidade)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(40, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setStyleSheet("background-color: rgb(122, 211, 103);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(45, 16777215))
        self.frame_5.setStyleSheet("background-color: rgb(179, 255, 120);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.verticalLayout_5.addWidget(self.textBrowser_8)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.verticalLayout_6.addWidget(self.textBrowser_9)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(162, 89, 24);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(45, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(18, 158, 57);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(280, 16777215))
        self.frame_7.setStyleSheet("background-color: rgb(51, 56, 36);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_8.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(58, -1, 8, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser_sodio = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_sodio.setMinimumSize(QtCore.QSize(85, 50))
        self.textBrowser_sodio.setMaximumSize(QtCore.QSize(80, 50))
        self.textBrowser_sodio.setObjectName("textBrowser_sodio")
        self.verticalLayout_4.addWidget(self.textBrowser_sodio)
        self.textBrowser_calcio = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_calcio.setMinimumSize(QtCore.QSize(85, 50))
        self.textBrowser_calcio.setMaximumSize(QtCore.QSize(85, 50))
        self.textBrowser_calcio.setObjectName("textBrowser_calcio")
        self.verticalLayout_4.addWidget(self.textBrowser_calcio)
        self.textBrowser_magnesio = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_magnesio.setMinimumSize(QtCore.QSize(85, 50))
        self.textBrowser_magnesio.setMaximumSize(QtCore.QSize(70, 50))
        self.textBrowser_magnesio.setObjectName("textBrowser_magnesio")
        self.verticalLayout_4.addWidget(self.textBrowser_magnesio)
        self.textBrowser_potassio = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_potassio.setMinimumSize(QtCore.QSize(85, 50))
        self.textBrowser_potassio.setMaximumSize(QtCore.QSize(85, 50))
        self.textBrowser_potassio.setObjectName("textBrowser_potassio")
        self.verticalLayout_4.addWidget(self.textBrowser_potassio)
        self.textBrowser_hidrogenio = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_hidrogenio.setMinimumSize(QtCore.QSize(85, 50))
        self.textBrowser_hidrogenio.setMaximumSize(QtCore.QSize(85, 50))
        self.textBrowser_hidrogenio.setObjectName("textBrowser_hidrogenio")
        self.verticalLayout_4.addWidget(self.textBrowser_hidrogenio)
        self.textBrowser_aluminoio = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_aluminoio.setMinimumSize(QtCore.QSize(85, 50))
        self.textBrowser_aluminoio.setMaximumSize(QtCore.QSize(85, 50))
        self.textBrowser_aluminoio.setObjectName("textBrowser_aluminoio")
        self.verticalLayout_4.addWidget(self.textBrowser_aluminoio)
        self.textBrowser_vesperado = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_vesperado.setMinimumSize(QtCore.QSize(85, 50))
        self.textBrowser_vesperado.setMaximumSize(QtCore.QSize(85, 50))
        self.textBrowser_vesperado.setObjectName("textBrowser_vesperado")
        self.verticalLayout_4.addWidget(self.textBrowser_vesperado)
        self.pushButton = QtWidgets.QPushButton(self.frame_8)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.mostra)
        self.verticalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setStyleSheet("background-color: rgb(120, 168, 88);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setContentsMargins(33, 3, -1, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_2)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_7)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_6)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_5)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_4)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_3)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_3.addWidget(self.doubleSpinBox)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("background-color: rgb(150, 105, 33);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(36, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_11.setStyleSheet("background-color: rgb(86, 171, 28);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser.setMinimumSize(QtCore.QSize(30, 60))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(30, 60))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_7.addWidget(self.textBrowser_3)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(30, 60))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_7.addWidget(self.textBrowser_4)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser_6.setMinimumSize(QtCore.QSize(30, 60))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.verticalLayout_7.addWidget(self.textBrowser_6)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(30, 60))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalLayout_7.addWidget(self.textBrowser_5)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(30, 60))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_7.addWidget(self.textBrowser_2)
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser_7.setMinimumSize(QtCore.QSize(30, 60))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.verticalLayout_7.addWidget(self.textBrowser_7)
        self.horizontalLayout_4.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setStyleSheet("background-color: rgb(186, 248, 51);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labels = QtWidgets.QLabel(self.frame_10)
        self.labels.setObjectName("labels")
        self.verticalLayout_8.addWidget(self.labels)
        self.label_h = QtWidgets.QLabel(self.frame_10)
        self.label_h.setObjectName("label_h")
        self.verticalLayout_8.addWidget(self.label_h)
        self.label_t = QtWidgets.QLabel(self.frame_10)
        self.label_t.setObjectName("label_t")
        self.verticalLayout_8.addWidget(self.label_t)
        self.label_v = QtWidgets.QLabel(self.frame_10)
        self.label_v.setObjectName("label_v")
        self.verticalLayout_8.addWidget(self.label_v)
        self.label_al = QtWidgets.QLabel(self.frame_10)
        self.label_al.setObjectName("label_al")
        self.verticalLayout_8.addWidget(self.label_al)
        self.label_na = QtWidgets.QLabel(self.frame_10)
        self.label_na.setObjectName("label_na")
        self.verticalLayout_8.addWidget(self.label_na)
        self.label_nc = QtWidgets.QLabel(self.frame_10)
        self.label_nc.setObjectName("label_nc")
        self.verticalLayout_8.addWidget(self.label_nc)
        self.horizontalLayout_4.addWidget(self.frame_10)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        Fertilidade.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Fertilidade)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 21))
        self.menubar.setObjectName("menubar")
        Fertilidade.setMenuBar(self.menubar)

        self.retranslateUi(Fertilidade)
        QtCore.QMetaObject.connectSlotsByName(Fertilidade)



    def mostra(self):

                conteudo1 = self.doubleSpinBox_2.value()

                conteudo2 = self.doubleSpinBox_7.value()

                conteudo3 = self.doubleSpinBox_6.value()

                conteudo4 = self.doubleSpinBox_5.value()

                conteudo5 = self.doubleSpinBox_4.value()

                conteudo6 = self.doubleSpinBox_3.value()

                conteudo7 = self.doubleSpinBox.value()

                S = (conteudo1 + conteudo2 + conteudo3 + conteudo4)

                H = conteudo5

                T = (S + H)

                V = (S/T)*100

                A = (conteudo6/(S + conteudo6))*100

                N = (conteudo1/T)*100

                NC = (T*(conteudo7 - V))/100


                self.labels.setNum(S)

                self.label_h.setNum(H)

                self.label_t.setNum(T)

                self.label_v.setNum(V)

                self.label_al.setNum(A)

                self.label_na.setNum(N)

                self.label_nc.setNum(NC)


    def retranslateUi(self, Fertilidade):
        _translate = QtCore.QCoreApplication.translate
        Fertilidade.setWindowTitle(_translate("Fertilidade", "MainWindow"))
        self.textBrowser_8.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Informações do perfil:</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Resultados</span></p></body></html>"))
        self.textBrowser_sodio.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">A quantidade de Na (cmol/dm³):</span></p></body></html>"))
        self.textBrowser_calcio.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Digite a quantidade de Ca  (cmol/dm³):</span></p></body></html>"))
        self.textBrowser_magnesio.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Digite a quantidade de Mg (cmol/dm³):</span></p></body></html>"))
        self.textBrowser_potassio.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Digite a quantidade de K  (cmol/dm³):</span></p></body></html>"))
        self.textBrowser_hidrogenio.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Digite a quantidade de H+Al  (cmol/dm³):</span></p></body></html>"))
        self.textBrowser_aluminoio.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Digite a quantidade de Al  (cmol/dm³):</span></p></body></html>"))
        self.textBrowser_vesperado.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Digite o valor de V esperado (%):</span></p></body></html>"))
        self.pushButton.setText(_translate("Fertilidade", "Entrar"))
        self.textBrowser.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Valor S:</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Valor H:</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Valor T:</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Valor V:</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Saturação por Al (%)  :</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Saturação por Na (%) :</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("Fertilidade", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Necessidade de Calagem:</span></p></body></html>"))
        self.labels.setText(_translate("Fertilidade", "TextLabel"))
        self.label_h.setText(_translate("Fertilidade", "TextLabel"))
        self.label_t.setText(_translate("Fertilidade", "TextLabel"))
        self.label_v.setText(_translate("Fertilidade", "TextLabel"))
        self.label_al.setText(_translate("Fertilidade", "TextLabel"))
        self.label_na.setText(_translate("Fertilidade", "TextLabel"))
        self.label_nc.setText(_translate("Fertilidade", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fertilidade = QtWidgets.QMainWindow()
    ui = Ui_Fertilidade()
    ui.setupUi(Fertilidade)
    Fertilidade.show()
    sys.exit(app.exec_())